import React from "react";
import type { UkWeightLossLocation } from "@/lib/data/uk-weight-loss-locations";
import UkLocationArticleClient from "@/components/blog/UkLocationArticleClient";

import BathLocationContent from "@/components/locations/content/BathLocationContent";
import BirminghamLocationContent from "@/components/locations/content/BirminghamLocationContent";
import BradfordLocationContent from "@/components/locations/content/BradfordLocationContent";
import BrightonAndHoveLocationContent from "@/components/locations/content/BrightonAndHoveLocationContent";
import BristolLocationContent from "@/components/locations/content/BristolLocationContent";
import CambridgeLocationContent from "@/components/locations/content/CambridgeLocationContent";
import CanterburyLocationContent from "@/components/locations/content/CanterburyLocationContent";
import CarlisleLocationContent from "@/components/locations/content/CarlisleLocationContent";
import ChelmsfordLocationContent from "@/components/locations/content/ChelmsfordLocationContent";
import ChesterLocationContent from "@/components/locations/content/ChesterLocationContent";
import ChichesterLocationContent from "@/components/locations/content/ChichesterLocationContent";
import ColchesterLocationContent from "@/components/locations/content/ColchesterLocationContent";
import CoventryLocationContent from "@/components/locations/content/CoventryLocationContent";
import DerbyLocationContent from "@/components/locations/content/DerbyLocationContent";
import DoncasterLocationContent from "@/components/locations/content/DoncasterLocationContent";
import DurhamLocationContent from "@/components/locations/content/DurhamLocationContent";
import ElyLocationContent from "@/components/locations/content/ElyLocationContent";
import ExeterLocationContent from "@/components/locations/content/ExeterLocationContent";
import GloucesterLocationContent from "@/components/locations/content/GloucesterLocationContent";
import HerefordLocationContent from "@/components/locations/content/HerefordLocationContent";
import KingstonUponHullLocationContent from "@/components/locations/content/KingstonUponHullLocationContent";
import LancasterLocationContent from "@/components/locations/content/LancasterLocationContent";
import LeedsLocationContent from "@/components/locations/content/LeedsLocationContent";
import LeicesterLocationContent from "@/components/locations/content/LeicesterLocationContent";
import LichfieldLocationContent from "@/components/locations/content/LichfieldLocationContent";
import LincolnLocationContent from "@/components/locations/content/LincolnLocationContent";
import LiverpoolLocationContent from "@/components/locations/content/LiverpoolLocationContent";
import LondonLocationContent from "@/components/locations/content/LondonLocationContent";
import ManchesterLocationContent from "@/components/locations/content/ManchesterLocationContent";
import MiltonKeynesLocationContent from "@/components/locations/content/MiltonKeynesLocationContent";
import NewcastleUponTyneLocationContent from "@/components/locations/content/NewcastleUponTyneLocationContent";
import NorwichLocationContent from "@/components/locations/content/NorwichLocationContent";
import NottinghamLocationContent from "@/components/locations/content/NottinghamLocationContent";
import OxfordLocationContent from "@/components/locations/content/OxfordLocationContent";
import PeterboroughLocationContent from "@/components/locations/content/PeterboroughLocationContent";
import PlymouthLocationContent from "@/components/locations/content/PlymouthLocationContent";
import PortsmouthLocationContent from "@/components/locations/content/PortsmouthLocationContent";
import PrestonLocationContent from "@/components/locations/content/PrestonLocationContent";
import RiponLocationContent from "@/components/locations/content/RiponLocationContent";
import SalfordLocationContent from "@/components/locations/content/SalfordLocationContent";
import SalisburyLocationContent from "@/components/locations/content/SalisburyLocationContent";
import SheffieldLocationContent from "@/components/locations/content/SheffieldLocationContent";
import SouthamptonLocationContent from "@/components/locations/content/SouthamptonLocationContent";
import SouthendOnSeaLocationContent from "@/components/locations/content/SouthendOnSeaLocationContent";
import StAlbansLocationContent from "@/components/locations/content/StAlbansLocationContent";
import StokeOnTrentLocationContent from "@/components/locations/content/StokeOnTrentLocationContent";
import SunderlandLocationContent from "@/components/locations/content/SunderlandLocationContent";
import TruroLocationContent from "@/components/locations/content/TruroLocationContent";
import WakefieldLocationContent from "@/components/locations/content/WakefieldLocationContent";
import WellsLocationContent from "@/components/locations/content/WellsLocationContent";
import WestminsterLocationContent from "@/components/locations/content/WestminsterLocationContent";
import WinchesterLocationContent from "@/components/locations/content/WinchesterLocationContent";
import WolverhamptonLocationContent from "@/components/locations/content/WolverhamptonLocationContent";
import WorcesterLocationContent from "@/components/locations/content/WorcesterLocationContent";
import YorkLocationContent from "@/components/locations/content/YorkLocationContent";
import ArmaghLocationContent from "@/components/locations/content/ArmaghLocationContent";
import BangorNorthernIrelandLocationContent from "@/components/locations/content/BangorNorthernIrelandLocationContent";
import BelfastLocationContent from "@/components/locations/content/BelfastLocationContent";
import LisburnLocationContent from "@/components/locations/content/LisburnLocationContent";
import LondonderryLocationContent from "@/components/locations/content/LondonderryLocationContent";
import NewryLocationContent from "@/components/locations/content/NewryLocationContent";
import AberdeenLocationContent from "@/components/locations/content/AberdeenLocationContent";
import DundeeLocationContent from "@/components/locations/content/DundeeLocationContent";
import DunfermlineLocationContent from "@/components/locations/content/DunfermlineLocationContent";
import EdinburghLocationContent from "@/components/locations/content/EdinburghLocationContent";
import GlasgowLocationContent from "@/components/locations/content/GlasgowLocationContent";
import InvernessLocationContent from "@/components/locations/content/InvernessLocationContent";
import PerthLocationContent from "@/components/locations/content/PerthLocationContent";
import StirlingLocationContent from "@/components/locations/content/StirlingLocationContent";
import BangorWalesLocationContent from "@/components/locations/content/BangorWalesLocationContent";
import CardiffLocationContent from "@/components/locations/content/CardiffLocationContent";
import NewportLocationContent from "@/components/locations/content/NewportLocationContent";
import StAsaphLocationContent from "@/components/locations/content/StAsaphLocationContent";
import StDavidsLocationContent from "@/components/locations/content/StDavidsLocationContent";
import SwanseaLocationContent from "@/components/locations/content/SwanseaLocationContent";
import WrexhamLocationContent from "@/components/locations/content/WrexhamLocationContent";
import ReadingLocationContent from "@/components/locations/content/ReadingLocationContent";
import NorthamptonLocationContent from "@/components/locations/content/NorthamptonLocationContent";
import LutonLocationContent from "@/components/locations/content/LutonLocationContent";
import BournemouthLocationContent from "@/components/locations/content/BournemouthLocationContent";
import SwindonLocationContent from "@/components/locations/content/SwindonLocationContent";
import HuddersfieldLocationContent from "@/components/locations/content/HuddersfieldLocationContent";
import MiddlesbroughLocationContent from "@/components/locations/content/MiddlesbroughLocationContent";
import WarringtonLocationContent from "@/components/locations/content/WarringtonLocationContent";
import BlackpoolLocationContent from "@/components/locations/content/BlackpoolLocationContent";
import BoltonLocationContent from "@/components/locations/content/BoltonLocationContent";
import OldhamLocationContent from "@/components/locations/content/OldhamLocationContent";
import RochdaleLocationContent from "@/components/locations/content/RochdaleLocationContent";
import StockportLocationContent from "@/components/locations/content/StockportLocationContent";
import WiganLocationContent from "@/components/locations/content/WiganLocationContent";
import WokingLocationContent from "@/components/locations/content/WokingLocationContent";
import BasildonLocationContent from "@/components/locations/content/BasildonLocationContent";
import CrawleyLocationContent from "@/components/locations/content/CrawleyLocationContent";
import SolihullLocationContent from "@/components/locations/content/SolihullLocationContent";
import BlackburnLocationContent from "@/components/locations/content/BlackburnLocationContent";
import PaisleyLocationContent from "@/components/locations/content/PaisleyLocationContent";
import EastKilbrideLocationContent from "@/components/locations/content/EastKilbrideLocationContent";
import LivingstonLocationContent from "@/components/locations/content/LivingstonLocationContent";
import CumbernauldLocationContent from "@/components/locations/content/CumbernauldLocationContent";
import MerthyrTydfilLocationContent from "@/components/locations/content/MerthyrTydfilLocationContent";
import NeathPortTalbotLocationContent from "@/components/locations/content/NeathPortTalbotLocationContent";
import CraigavonLocationContent from "@/components/locations/content/CraigavonLocationContent";

type Props = {
  slug: string;
  loc: UkWeightLossLocation;
  shareUrl: string;
};

export default function LocationContentRenderer({ slug, loc, shareUrl }: Props) {
  if (slug === "bath") return <BathLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "birmingham") return <BirminghamLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bradford") return <BradfordLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "brighton-and-hove") return <BrightonAndHoveLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bristol") return <BristolLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "cambridge") return <CambridgeLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "canterbury") return <CanterburyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "carlisle") return <CarlisleLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "chelmsford") return <ChelmsfordLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "chester") return <ChesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "chichester") return <ChichesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "colchester") return <ColchesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "coventry") return <CoventryLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "derby") return <DerbyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "doncaster") return <DoncasterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "durham") return <DurhamLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "ely") return <ElyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "exeter") return <ExeterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "gloucester") return <GloucesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "hereford") return <HerefordLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "kingston-upon-hull") return <KingstonUponHullLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "lancaster") return <LancasterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "leeds") return <LeedsLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "leicester") return <LeicesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "lichfield") return <LichfieldLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "lincoln") return <LincolnLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "liverpool") return <LiverpoolLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "london") return <LondonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "manchester") return <ManchesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "milton-keynes") return <MiltonKeynesLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "newcastle-upon-tyne") return <NewcastleUponTyneLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "norwich") return <NorwichLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "nottingham") return <NottinghamLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "oxford") return <OxfordLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "peterborough") return <PeterboroughLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "plymouth") return <PlymouthLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "portsmouth") return <PortsmouthLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "preston") return <PrestonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "ripon") return <RiponLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "salford") return <SalfordLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "salisbury") return <SalisburyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "sheffield") return <SheffieldLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "southampton") return <SouthamptonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "southend-on-sea") return <SouthendOnSeaLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "st-albans") return <StAlbansLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "stoke-on-trent") return <StokeOnTrentLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "sunderland") return <SunderlandLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "truro") return <TruroLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "wakefield") return <WakefieldLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "wells") return <WellsLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "westminster") return <WestminsterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "winchester") return <WinchesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "wolverhampton") return <WolverhamptonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "worcester") return <WorcesterLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "york") return <YorkLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "armagh") return <ArmaghLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bangor-northern-ireland") return <BangorNorthernIrelandLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "belfast") return <BelfastLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "lisburn") return <LisburnLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "londonderry") return <LondonderryLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "newry") return <NewryLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "aberdeen") return <AberdeenLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "dundee") return <DundeeLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "dunfermline") return <DunfermlineLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "edinburgh") return <EdinburghLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "glasgow") return <GlasgowLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "inverness") return <InvernessLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "perth") return <PerthLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "stirling") return <StirlingLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bangor-wales") return <BangorWalesLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "cardiff") return <CardiffLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "newport") return <NewportLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "st-asaph") return <StAsaphLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "st-davids") return <StDavidsLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "swansea") return <SwanseaLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "wrexham") return <WrexhamLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "reading") return <ReadingLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "northampton") return <NorthamptonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "luton") return <LutonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bournemouth") return <BournemouthLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "swindon") return <SwindonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "huddersfield") return <HuddersfieldLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "middlesbrough") return <MiddlesbroughLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "warrington") return <WarringtonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "blackpool") return <BlackpoolLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "bolton") return <BoltonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "oldham") return <OldhamLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "rochdale") return <RochdaleLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "stockport") return <StockportLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "wigan") return <WiganLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "woking") return <WokingLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "basildon") return <BasildonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "crawley") return <CrawleyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "solihull") return <SolihullLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "blackburn") return <BlackburnLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "paisley") return <PaisleyLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "east-kilbride") return <EastKilbrideLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "livingston") return <LivingstonLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "cumbernauld") return <CumbernauldLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "merthyr-tydfil") return <MerthyrTydfilLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "neath-port-talbot") return <NeathPortTalbotLocationContent loc={loc} shareUrl={shareUrl} />;
  if (slug === "craigavon") return <CraigavonLocationContent loc={loc} shareUrl={shareUrl} />;

  // Fallback if not found
  return <UkLocationArticleClient loc={loc} shareUrl={shareUrl} />;
}
